<?php
/**
 * Created by PhpStorm.
 * User: fedornabilkin
 * Date: 09.01.2022
 * Time: 17:41
 */

use yii\rest\UrlRule;

return [
    [
        'class' => UrlRule::class,
        'controller' => ['v1/world'],
        'pluralize' => false,
        'only' => ['construction', 'construction-preview', 'construction-execute', 'equipment-wear', 'housing', 'housing-preview', 'housing-execute', 'garden', 'garden-preview', 'garden-execute', 'equipment-expansion', 'equipment-expand-preview', 'equipment-expand', 'nights', 'shelter', 'shelter-preview', 'shelter-execute', 'premises', 'premises-publish-preview', 'premises-publish', 'premises-buy-preview', 'premises-buy', 'premises-withdraw-preview', 'premises-withdraw', 'index', 'options', 'node', 'children', 'navigation', 'map', 'statistics', 'actions', 'onboarding', 'join-preview', 'join', 'move-preview', 'move', 'archive-preview', 'archive', 'storages', 'storage', 'storage-transfer-preview', 'storage-transfer', 'chest-repair-preview', 'chest-repair', 'workspace', 'workspace-preview', 'workspace-craft', 'recovery', 'recovery-preview', 'recover', 'economy', 'invest-preview', 'invest', 'obligations', 'collect-preview', 'collect', 'pay-preview', 'pay', 'finance-policy-preview', 'finance-policy', 'orders', 'order-items', 'order-stock', 'order-publish-preview', 'order-publish', 'order-deliver-preview', 'order-deliver', 'order-cancel-preview', 'order-cancel'],
        'extraPatterns' => [
            'GET nodes/<id:\d+>/construction' => 'construction',
            'POST nodes/<id:\d+>/construction-<operation:pause|resume|cancel>-preview' => 'construction-preview',
            'POST nodes/<id:\d+>/construction-<operation:pause|resume|cancel>' => 'construction-execute',
            'GET equipment/<id:\d+>/wear' => 'equipment-wear',
            'GET nodes/<id:\d+>/housing' => 'housing',
            'POST nodes/<id:\d+>/housing-<operation:lodge|leave>-preview' => 'housing-preview',
            'POST nodes/<id:\d+>/housing-<operation:lodge|leave>' => 'housing-execute',
            'GET nodes/<id:\d+>/nights' => 'nights',
            'GET nodes/<id:\d+>/shelter' => 'shelter',
            'POST nodes/<id:\d+>/shelter-<operation:claim|deploy|fold|lodge|leave|repair>-preview' => 'shelter-preview',
            'POST nodes/<id:\d+>/shelter-<operation:claim|deploy|fold|lodge|leave|repair>' => 'shelter-execute',
            'GET nodes/<id:\d+>/garden' => 'garden',
            'GET nodes/<id:\d+>/equipment-expansion' => 'equipment-expansion',
            'POST nodes/<id:\d+>/equipment-expand-preview' => 'equipment-expand-preview',
            'POST nodes/<id:\d+>/equipment-expand' => 'equipment-expand',
            'POST nodes/<id:\d+>/garden-<operation:publish|withdraw|buy|expand>-preview' => 'garden-preview',
            'POST nodes/<id:\d+>/garden-<operation:publish|withdraw|buy|expand>' => 'garden-execute',
            'GET nodes/<id:\d+>/premises' => 'premises',
            'POST nodes/<id:\d+>/premises-publish-preview' => 'premises-publish-preview',
            'POST nodes/<id:\d+>/premises-publish' => 'premises-publish',
            'POST nodes/<id:\d+>/premises-buy-preview' => 'premises-buy-preview',
            'POST nodes/<id:\d+>/premises-buy' => 'premises-buy',
            'POST nodes/<id:\d+>/premises-withdraw-preview' => 'premises-withdraw-preview',
            'POST nodes/<id:\d+>/premises-withdraw' => 'premises-withdraw',
            'GET nodes/<id:\d+>/economy' => 'economy',
            'GET nodes/<id:\d+>/orders' => 'orders',
            'GET nodes/<id:\d+>/order-items' => 'order-items',
            'GET nodes/<id:\d+>/order-stock' => 'order-stock',
            'POST nodes/<id:\d+>/order-publish-preview' => 'order-publish-preview',
            'POST nodes/<id:\d+>/order-publish' => 'order-publish',
            'POST nodes/<id:\d+>/order-deliver-preview' => 'order-deliver-preview',
            'POST nodes/<id:\d+>/order-deliver' => 'order-deliver',
            'POST nodes/<id:\d+>/order-cancel-preview' => 'order-cancel-preview',
            'POST nodes/<id:\d+>/order-cancel' => 'order-cancel',
            'GET nodes/<id:\d+>/obligations' => 'obligations',
            'POST nodes/<id:\d+>/collect-preview' => 'collect-preview',
            'POST nodes/<id:\d+>/collect' => 'collect',
            'POST nodes/<id:\d+>/pay-preview' => 'pay-preview',
            'POST nodes/<id:\d+>/pay' => 'pay',
            'POST nodes/<id:\d+>/finance-policy-preview' => 'finance-policy-preview',
            'POST nodes/<id:\d+>/finance-policy' => 'finance-policy',
            'POST nodes/<id:\d+>/invest-preview' => 'invest-preview',
            'POST nodes/<id:\d+>/invest' => 'invest',
            'GET workspace' => 'workspace',
            'GET storage/recovery' => 'recovery',
            'POST storage/recovery-preview' => 'recovery-preview',
            'POST storage/recover' => 'recover',
            'POST workspace/preview' => 'workspace-preview',
            'POST workspace/craft' => 'workspace-craft',
            'GET storages' => 'storages',
            'GET storage/<id:\d+>' => 'storage',
            'POST storage/transfer-preview' => 'storage-transfer-preview',
            'POST storage/transfer' => 'storage-transfer',
            'POST storage/chest-repair-preview' => 'chest-repair-preview',
            'POST storage/chest-repair' => 'chest-repair',
            'GET onboarding' => 'onboarding',
            'POST onboarding/preview' => 'join-preview',
            'POST onboarding/join' => 'join',
            'GET nodes/<id:\d+>' => 'node',
            'GET nodes/<id:\d+>/children' => 'children',
            'GET nodes/<id:\d+>/navigation' => 'navigation',
            'GET nodes/<id:\d+>/map' => 'map',
            'GET nodes/<id:\d+>/statistics' => 'statistics',
            'GET nodes/<id:\d+>/actions' => 'actions',
            'POST nodes/<id:\d+>/move-preview' => 'move-preview',
            'POST nodes/<id:\d+>/move' => 'move',
            'POST nodes/<id:\d+>/archive-preview' => 'archive-preview',
            'POST nodes/<id:\d+>/archive' => 'archive',
            'OPTIONS <path:.*>' => 'options',
        ],
    ],
    [
        'class' => UrlRule::class,
        'controller' => ['v1/user'],
        'only' => ['index', 'wall', 'wall-update', 'data', 'profile', 'last', 'online', 'online-count', 'referrals', 'heartbeat', 'visited'],
        'extraPatterns' => [
            'GET data' => 'data',
            'GET profile' => 'profile',
            'GET last' => 'last',
            'GET online' => 'online',
            'GET online-count' => 'online-count',
            'GET visited' => 'visited',
            'GET referrals' => 'referrals',
            'POST heartbeat' => 'heartbeat',
            'GET wall/<login:[-a-zA-Z0-9_\.@]+>' => 'wall',
            'PATCH wall' => 'wall-update',
        ],
    ],
    [
        'class' => UrlRule::class,
        'controller' => ['v1/tips'],
        'pluralize' => false,
        'only' => ['random'],
        'extraPatterns' => ['GET random' => 'random'],
    ],
    [
        'class' => UrlRule::class,
        'controller' => ['v1/history'],
        'only' => ['index', 'create', 'balance', 'balance-type', 'rating', 'rating-type'],
        'pluralize' => false,
        'extraPatterns' => [
            'GET balance' => 'balance',
            'GET balance-type' => 'balance-type',
            'GET rating' => 'rating',
            'GET rating-type' => 'rating-type',
        ],
    ],
    [
        'class' => UrlRule::class,
        'controller' => ['v1/rating'],
        'pluralize' => false,
        'only' => ['everyday'],
        'extraPatterns' => [
            'GET everyday' => 'everyday',
        ],
    ],
    [
        'class' => UrlRule::class,
        'controller' => ['v1/stat'],
        'pluralize' => false,
        'only' => ['index', 'top', 'user', 'recent-games'],
        'extraPatterns' => [
            'GET recent-games' => 'recent-games',
            'GET top' => 'top',
            'GET user/<login:[-a-zA-Z0-9_\.@]+>' => 'user',
        ],
    ],
    [
        'class' => UrlRule::class,
        'controller' => ['v1/bonus'],
        'pluralize' => false,
        'only' => ['everyday', 'recipients', 'fund', 'my-fund', 'available'],
        'extraPatterns' => [
            'GET everyday' => 'everyday',
            'GET recipients' => 'recipients',
            'GET fund' => 'fund',
            'GET my-fund' => 'my-fund',
            'GET available' => 'available',
        ],
    ],
//    [
//        'class' => UrlRule::class,
//        'controller' => 'v1/catalog',
//        'only' => [
//            'pay-types',
//            'order-statuses',
//            'product-statuses',
//            'pay-statuses',
//            'tare-types',
//            'customer-requests',
//            'change-reasons'
//        ],
//        'extraPatterns' => [
//            'GET pay-types' => 'pay-types',
//            'GET order-statuses' => 'order-statuses',
//            'GET product-statuses' => 'product-statuses',
//            'GET pay-statuses' => 'pay-statuses',
//            'GET tare-types' => 'tare-types',
//            'GET customer-requests' => 'customer-requests',
//            'GET change-reasons' => 'change-reasons',
//        ],
//    ],
//    [
//        'class' => UrlRule::class,
//        'controller' => 'v1/order',
//        'only' => [
//            'create',
//            'view',
//            'view-fpa',
//            'index',
//            'get',
//            'cancel',
//            'status',
//            'payment',
//            'send-code',
//            'ready-list',
//            'send-file',
//            'by-promos',
//        ],
//        'extraPatterns' => [
//            'POST get/<id:\d+>' => 'view',
//            'GET view-fpa/<id:\d+>' => 'view-fpa',
//            'POST get' => 'index',
//            'POST cancel' => 'cancel',
//            'POST status' => 'status',
//            'POST payment' => 'payment',
//            'POST <orderId:\d+>/sendcode' => 'send-code',
//            'GET readylist/<pfm:[0-9a-zA-Z\-]+>' => 'ready-list',
//            'POST <orderId:\d+>/sendfile' => 'send-file',
//            'GET by-promos' => 'by-promos',
//        ],
//    ],
];
