version: "3"
volumes:
  postgresdata:
services:
  nginx:
    image: nginx:1.15
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./docker/nginx/add/:/etc/nginx/add/
      - ./yii2/:/web/yii2/
    ports:
      - ${PORT_NGINX_API}:80
      - ${PORT_NGINX_FRONT}:88
      - ${PORT_NGINX_ADMIN}:8080
    links:
      - php

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./yii2/:/web/yii2/
      - ./.env:/etc/environment
      - ./docker/php/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    ports:
      - 9000

  composer:
    build:
      context: docker/composer
      dockerfile: Dockerfile
    volumes:
      - ./yii2/:/web/yii2/
      - ./docker/composer/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  postgres:
    image: postgres:11
    ports:
      - ${PG_DB_PORT}:5432
    volumes:
      - postgresdata:/data/postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_DB: ${PG_DB_NAME}
