<?php
return [
    'account-api' => ['class' => \common\modules\world\apiControllers\AccountApiController::class],
    'supply-api' => ['class' => \common\modules\world\apiControllers\SupplyApiController::class],
    'start-api' => ['class' => \common\modules\world\apiControllers\StartApiController::class],
    'event-api' => ['class' => \common\modules\world\apiControllers\EventApiController::class],
    'build-api' => ['class' => \common\modules\world\apiControllers\BuildApiController::class],
    'template-api' => ['class' => \common\modules\world\apiControllers\TemplateApiController::class],
    'object-api' => ['class' => \common\modules\world\apiControllers\ObjectApiController::class],
    'api-node' => ['class' => \common\modules\world\apiControllers\NodeController::class],
    'api-membership' => ['class' => \common\modules\world\apiControllers\MembershipController::class],
    'api-storage' => ['class' => \common\modules\world\apiControllers\StorageController::class],
    'api-workspace' => ['class' => \common\modules\world\apiControllers\WorkspaceController::class],
    'api-budget' => ['class' => \common\modules\world\apiControllers\BudgetController::class],
    'api-finance' => ['class' => \common\modules\world\apiControllers\FinanceController::class],
    'api-order' => ['class' => \common\modules\world\apiControllers\OrderController::class],
    'api-shelter' => ['class' => \common\modules\world\apiControllers\ShelterController::class],
    'api-housing' => ['class' => \common\modules\world\apiControllers\HousingController::class],
    'api-garden' => ['class' => \common\modules\world\apiControllers\GardenController::class],
    'api-cultivation' => ['class' => \common\modules\world\apiControllers\CultivationController::class],
    'api-harvest' => ['class' => \common\modules\world\apiControllers\HarvestController::class],
    'api-warehouse' => ['class' => \common\modules\world\apiControllers\WarehouseController::class],
    'api-premises' => ['class' => \common\modules\world\apiControllers\PremisesController::class],
    'api-construction' => ['class' => \common\modules\world\apiControllers\ConstructionController::class],
    'api-building' => ['class' => \common\modules\world\apiControllers\BuildingController::class],
    'api-demolition' => ['class' => \common\modules\world\apiControllers\DemolitionController::class],
    'api-notification' => ['class' => \common\modules\world\apiControllers\NotificationController::class],
    'api-profession' => ['class' => \common\modules\world\apiControllers\ProfessionController::class],
    'api-achievement' => ['class' => \common\modules\world\apiControllers\AchievementController::class],
];
