<?php
use yii\db\Query;
// Included in the real engine suite on SQLite and the allowlisted MySQL/PostgreSQL CI database.
$storageTx=$db->beginTransaction();
$migrationTx=$db->beginTransaction();
$db->createCommand()->delete('craft_capacity',['user_id'=>9002])->execute();
$legacyChest=$s->insert('craft_inventory',['user_id'=>9002,'item_id'=>$items['classic-chest']['id'],'item_quantity'=>3,'slot'=>102]);
ob_start();(new \m260924_160000_craft_storage(['db'=>$db]))->up();ob_end_clean();
$converted=$engine->state(9002);
checkCraft(count($converted['containers'])===3&&array_sum(array_column($converted['inventory_slots'],'quantity'))===10,'migration splits legacy chest stacks without losing original materials');
ob_start();(new \m260924_160000_craft_storage(['db'=>$db]))->up();ob_end_clean();
checkCraft($engine->state(9002)['inventory_slots']===$converted['inventory_slots'],'repeated migration does not duplicate old chests');
$migrationTx->rollBack();
$inv=new \common\modules\craft\service\CraftInventory($s);
$inventoryTotal=static function()use($db){return (int)(new Query())->from('craft_inventory')->where(['user_id'=>9001])->sum('item_quantity',$db);};
$inv->synchronize(9001);
$state=$engine->state(9001);
checkCraft($state['slot_limit']===50&&$state['active_slots']===20&&$state['permanent_slots']===20,'new backpack has 50 cells, 20 active');
$bought=$engine->command(9001,'buy-inventory-slot','buy_slots',['quantity'=>2,'unit_price'=>10]);
checkCraft($bought['state']['credit']===80.0&&$bought['state']['permanent_slots']===22,'permanent slots debit unified credit at configured price');
$again=$engine->command(9001,'buy-inventory-slot','buy_slots',['quantity'=>2,'unit_price'=>10]);
checkCraft($again['replayed']&&$again['state']['credit']===80.0&&$again['state']['permanent_slots']===22,'slot purchase retry cannot charge twice');
class FailedSlotStorage extends \common\modules\craft\service\CraftStorage { public function insert(string $table,array $values): int {if($table==='craft_command')throw new \RuntimeException('slot failure');return parent::insert($table,$values);} }
try{(new \common\modules\craft\service\Crafting(new FailedSlotStorage($db)))->command(9001,'failed-slot-purchase','buy_slots',['quantity'=>1,'unit_price'=>10]);throw new \LogicException('failure expected');}catch(\RuntimeException $error){if($error->getMessage()!=='slot failure')throw $error;}
checkCraft($engine->state(9001)['credit']===80.0&&$engine->state(9001)['permanent_slots']===22&&(int)(new Query())->from('history_balance')->where(['user_id'=>9001,'type'=>'craft_slots'])->count('*',$db)===1,'late purchase failure rolls back credit, slots and balance history');
rejectsCraft(function()use($engine){$engine->command(9001,'buy-stale-price-key','buy_slots',['quantity'=>1,'unit_price'=>0]);},'stale or manipulated slot price rejected');
rejectsCraft(function()use($engine){$engine->command(9001,'buy-over-limit-key','buy_slots',['quantity'=>29,'unit_price'=>10]);},'cannot purchase beyond 50 permanent cells');
$material=$items['classic-log'];$chestItem=$items['classic-chest'];$elixir=$items['classic-space-elixir'];
$s->move(9001,$material,50);$s->move(9001,$chestItem,2);$s->move(9001,$elixir,1);
$state=$engine->state(9001);$chestId=$state['containers'][0]['id'];$foreignChest=$s->insert('craft_inventory',['user_id'=>9002,'item_id'=>$chestItem['id'],'item_quantity'=>1,'slot'=>2]);
$source=(int)(new Query())->select('id')->from('craft_inventory')->where(['user_id'=>9001,'item_id'=>$material['id']])->scalar($db);
$body=['id'=>(int)$material['id'],'slot_id'=>$source,'quantity'=>20,'container_id'=>$chestId,'position'=>1];
$deposited=$engine->command(9001,'chest-deposit-key','transfer',$body);$container=$deposited['state']['containers'][0];
checkCraft($container['capacity']===10&&$container['durability']===99&&$container['slots'][0]['quantity']===20,'chest stores transferred material and wears once per deposit');
checkCraft($s->quantities(9001)[(int)$material['id']]===30,'craft resources exclude chest contents');
$engine->command(9001,'chest-deposit-key','transfer',$body);
checkCraft($engine->state(9001)['containers'][0]['durability']===99&&$inventoryTotal()===53,'repeated transfer preserves total quantities and durability');
$foreign=$body;$foreign['container_id']=$foreignChest;
rejectsCraft(function()use($engine,$foreign){$engine->command(9001,'chest-foreign-key','transfer',$foreign);},'cannot deposit into another account chest');
$nested=['id'=>(int)$chestItem['id'],'slot_id'=>$chestId,'quantity'=>1,'container_id'=>$state['containers'][1]['id'],'position'=>1];
rejectsCraft(function()use($engine,$nested){$engine->command(9001,'chest-nesting-key','transfer',$nested);},'nested chests rejected');
rejectsCraft(function()use($engine,$chestItem,$chestId){$engine->command(9001,'chest-discard-full','discard',['id'=>(int)$chestItem['id'],'slot_id'=>$chestId]);},'filled chest cannot be deleted');
$db->createCommand()->update('craft_container',['durability'=>0],['id'=>$chestId])->execute();
rejectsCraft(function()use($engine,$body){$engine->command(9001,'broken-chest-deposit','transfer',$body);},'broken chest rejects deposits');
$withdraw=['id'=>(int)$material['id'],'slot_id'=>$container['slots'][0]['id'],'quantity'=>20,'container_id'=>0,'position'=>1];
$result=$engine->command(9001,'broken-chest-withdraw','transfer',$withdraw);
checkCraft(!$result['state']['containers'][0]['slots']&&$s->quantities(9001)[(int)$material['id']]===50,'broken chest permits retrieval without losing contents');
$used=$engine->command(9001,'elixir-unlock-key','use',['id'=>(int)$elixir['id']]);
checkCraft($used['state']['active_slots']===27&&abs($used['state']['slots_expire_at']-time()-7*86400)<=2,'elixir opens five slots for seven days');
$db->createCommand()->delete('craft_inventory',['user_id'=>9001])->execute();
$db->createCommand()->delete('craft_container',['user_id'=>9001])->execute();
for($i=1;$i<=27;$i++)$s->insert('craft_inventory',['user_id'=>9001,'item_id'=>$material['id'],'item_quantity'=>100,'slot'=>$i]);
$db->createCommand()->update('craft_slot_lease',['expires_at'=>time()-1],['user_id'=>9001])->execute();
$expired=$engine->state(9001);
checkCraft($expired['active_slots']===22&&$expired['slots_used']===27&&$inventoryTotal()===2700,'expiry preserves every item in inactive slots');
checkCraft(count(array_filter($expired['inventory_slots'],static function($slot){return !$slot['active'];}))===5,'expired occupied slots remain explicitly visible');
$empty=$expired['inventory_slots'][0]['id'];
$result=$engine->command(9001,'free-expired-cell-key','discard',['id'=>(int)$material['id'],'slot_id'=>$empty,'quantity'=>100]);
checkCraft($result['state']['slots_used']===26&&$inventoryTotal()===2600&&count(array_filter($result['state']['inventory_slots'],static function($slot){return !$slot['active'];}))===4,'held items automatically fill a freed active cell');
rejectsCraft(function()use($engine,$material,$result){$engine->command(9001,'inactive-target-cell','transfer',['id'=>(int)$material['id'],'slot_id'=>$result['state']['inventory_slots'][0]['id'],'quantity'=>1,'container_id'=>0,'position'=>30]);},'cannot put a new item in a closed cell');
$storageTx->rollBack();
